36: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which 
uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.        
  model.load_state_dict(torch.load('u2net_epoch_100.pth', map_location=device))
C:\Users\siyiliu2\Desktop\cnnv3\U-2-Net\model\u2net.py:23: UserWarning: `nn.functional.upsample` is deprecated. Use `nn.functional.interpolate` instead.   
  src = F.upsample(src,size=tar.shape[2:],mode='bilinear')
Traceback (most recent call last):
  File "C:\Users\siyiliu2\Desktop\cnnv3\U-2-Net\test.py", line 41, in <module>
    for batch in test_loader:
  File "C:\Users\siyiliu2\AppData\Local\anaconda3\envs\cnn\lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__   
    data = self._next_data()
  File "C:\Users\siyiliu2\AppData\Local\anaconda3\envs\cnn\lib\site-packages\torch\utils\data\dataloader.py", line 757, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\siyiliu2\AppData\Local\anaconda3\envs\cnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\siyiliu2\AppData\Local\anaconda3\envs\cnn\lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\siyiliu2\Desktop\cnnv3\U-2-Net\data_loader.py", line 296, in __getitem__
    image = Image.open(img_path).convert('RGB')
  File "C:\Users\siyiliu2\AppData\Local\anaconda3\envs\cnn\lib\site-packages\PIL\Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '../dataset/images/test/FP11_6_X20_01 - Shortcut.lnk'
